version: 2

project_name: bluetooth-sniffer

builds:
  - id: bluetooth-sniffer
    binary: bluetooth-sniffer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: bluetooth-sniffer
    builds:
      - bluetooth-sniffer
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: nxm
    name: bluetooth-sniffer